# Based on:
# https://community.home-assistant.io/t/zha-tuya-4-button-scene-switch-ts0044/265099/62
# https://community.home-assistant.io/t/blueprint-moes-scene-switch-zigbee-tz3000-wkai4ga5/646195

blueprint:
  name: ZHA - Tuya 4-Button Scene Switch MOES
  description: |
    Automate your Moes 4-Button Scene Switch (TS0044) using ZHA events.
  domain: automation
  input:
    tuya_4button_scene_switch:
      name: Tuya 4-Button Scene Switch
      description: Tuya 4-Button Scene Switch to use
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_wkai4ga5
          model: TS0044
          multiple: false

    # --- Button 1 Actions ---
    button_1:
      name: Button 1 (Upper-left) configuration
      collapsed: false
      input:
        button_1_short_press:
          name: Single Press
          description: Action to run on button 1 (Upper-left) single press
          default: []
          selector:
            action: {}
        button_1_double_press:
          name: Double Press
          description: Action to run on button 1 (Upper-left) double press
          default: []
          selector:
            action: {}
        button_1_long_press:
          name: Long Press
          description: Action to run on button 1 (Upper-left) long press
          default: []
          selector:
            action: {}
    # --- Button 2 Actions ---
    button_2:
      name: Button 2 (Upper-right) configuration
      collapsed: false
      input:
        button_2_short_press:
          name: Single Press
          description: Action to run on button 2 (Upper-right) single press
          default: []
          selector:
            action: {}
        button_2_double_press:
          name: Double Press
          description: Action to run on button 2 (Upper-right) double press
          default: []
          selector:
            action: {}
        button_2_long_press:
          name: Long Press
          description: Action to run on button 2 (Upper-right) long press
          default: []
          selector:
            action: {}
    # --- Button 3 Actions ---
    button_3:
      name: Button 3 (Lower-left) configuration
      collapsed: false
      input:
        button_3_short_press:
          name: Single Press
          description: Action to run on button 3 (Lower-left) single press
          default: []
          selector:
            action: {}
        button_3_double_press:
          name: Double Press
          description: Action to run on button 3 (Lower-left) double press
          default: []
          selector:
            action: {}
        button_3_long_press:
          name: Long Press
          description: Action to run on button 3 (Lower-left) long press
          default: []
          selector:
            action: {}
    # --- Button 4 Actions ---
    button_4:
      name: Button 4 (Lower-right) configuration
      collapsed: false
      input:
        button_4_short_press:
          name: Single Press
          description: Action to run on button 4 (Lower-right) single press
          default: []
          selector:
            action: {}
        button_4_double_press:
          name: Double Press
          description: Action to run on button 4 (Lower-right) double press
          default: []
          selector:
            action: {}
        button_4_long_press:
          name: Long Press
          description: Action to run on button 4 (Lower-right) long press
          default: []
          selector:
            action: {}
  source_url: https://github.com/wiktor2200/ha_blueprints/blob/main/ZHA_Moes_4button_scenes_blueprint.yaml

mode: parallel
max: 10
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input tuya_4button_scene_switch

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"

  - choose:
      # --- SHORT PRESS ---
      - conditions: "{{ command == 'remote_button_short_press' }}"
        sequence:
          - choose:
              - conditions: "{{ endpoint_id == 1 }}"
                sequence: !input button_1_short_press
              - conditions: "{{ endpoint_id == 2 }}"
                sequence: !input button_2_short_press
              - conditions: "{{ endpoint_id == 3 }}"
                sequence: !input button_3_short_press
              - conditions: "{{ endpoint_id == 4 }}"
                sequence: !input button_4_short_press

      # --- DOUBLE PRESS ---
      - conditions: "{{ command == 'remote_button_double_press' }}"
        sequence:
          - choose:
              - conditions: "{{ endpoint_id == 1 }}"
                sequence: !input button_1_double_press
              - conditions: "{{ endpoint_id == 2 }}"
                sequence: !input button_2_double_press
              - conditions: "{{ endpoint_id == 3 }}"
                sequence: !input button_3_double_press
              - conditions: "{{ endpoint_id == 4 }}"
                sequence: !input button_4_double_press

      # --- LONG PRESS ---
      - conditions: "{{ command == 'remote_button_long_press' }}"
        sequence:
          - choose:
              - conditions: "{{ endpoint_id == 1 }}"
                sequence: !input button_1_long_press
              - conditions: "{{ endpoint_id == 2 }}"
                sequence: !input button_2_long_press
              - conditions: "{{ endpoint_id == 3 }}"
                sequence: !input button_3_long_press
              - conditions: "{{ endpoint_id == 4 }}"
                sequence: !input button_4_long_press
