# Based on:
# https://community.home-assistant.io/t/zha-tuya-4-button-scene-switch-ts0044/265099/62
# https://community.home-assistant.io/t/blueprint-moes-scene-switch-zigbee-tz3000-wkai4ga5/646195

blueprint:
  name: ZHA - Tuya 4-Button Scene Switch MOES
  description: Automate your Tuya 4-Button Scene Switch using ZHA events.
  domain: automation
  input:
    tuya_4button_scene_switch:
      name: Tuya 4-Button Scene Switch
      description: Tuya 4-Button Scene Switch to use
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_wkai4ga5
          model: TS0044
          multiple: false
    lights_settings:
      name: Lights settings (optional)
      collapsed: true
      input:
        light1_target:
          name: First light to manage
          selector:
            target:
              entity:
                domain: light
        light1_init_brightness:
          name: First light initial brightness
          description: Initial brightness when turned on
          default: 50
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"
        light1_brightness_step:
          name: First light brightness step
          description: Brightness step when changed
          default: 20
          selector:
            number:
              min: 5
              max: 30
              unit_of_measurement: "%"
        light2_target:
          name: Second light to manage
          selector:
            target:
              entity:
                domain: light
        light2_init_brightness:
          name: Second light initial brightness
          description: Initial brightness when turned on
          default: 50
          selector:
            number:
              min: 1
              max: 100
              unit_of_measurement: "%"
        light2_brightness_step:
          name: Second light brightness step
          description: Brightness step when changed
          default: 20
          selector:
            number:
              min: 5
              max: 30
              unit_of_measurement: "%"
    button_one:
      name: Button 1 (Upper-left) configuration
      collapsed: true
      input:
        button_one_short_press:
          name: Single Press
          description: Action to run on button 1 (Upper-left) single press
          default:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_pct: !input light1_init_brightness
              target:
                entity_id: !input light1_target
          selector:
            action: {}
        button_one_double_press:
          name: Double Press
          description: Action to run on button 1 (Upper-left) double press
          default:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_step_pct: !input light1_brightness_step
              target:
                entity_id: !input light1_target
          selector:
            action: {}
        button_one_long_press:
          name: Long Press
          description: Action to run on button 1 (Upper-left) long press
          default:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_pct: 100
              target:
                entity_id: !input light1_target
          selector:
            action: {}
    button_two:
      name: Button 2 (Upper-right) configuration
      collapsed: true
      input:
        button_two_short_press:
          name: Single Press
          description: Action to run on button 2 (Upper-right) single press
          default:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_pct: 50
              target:
                entity_id: !input light2_target
          selector:
            action: {}
        button_two_double_press:
          name: Double Press
          description: Action to run on button 2 (Upper-right) double press
          default:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_step_pct: 20
              target:
                entity_id: !input light2_target
          selector:
            action: {}
        button_two_long_press:
          name: Long Press
          description: Action to run on button 2 (Upper-right) long press
          default:
            - action: light.turn_on
              metadata: {}
              data:
                brightness_pct: 100
              target:
                entity_id: !input light2_target
          selector:
            action: {}
    button_three:
      name: Button 3 (Lower-left) configuration
      collapsed: true
      input:
        button_three_short_press:
          name: Single Press
          description: Action to run on button 3 (Lower-left) single press
          default: []
          selector:
            action: {}
        button_three_double_press:
          name: Double Press
          description: Action to run on button 3 (Lower-left) double press
          default: []
          selector:
            action: {}
        button_three_long_press:
          name: Long Press
          description: Action to run on button 3 (Lower-left) long press
          default: []
          selector:
            action: {}
    button_four:
      name: Button 4 (Lower-right) configuration
      collapsed: true
      input:
        button_four_short_press:
          name: Single Press
          description: Action to run on button 4 (Lower-right) single press
          default: []
          selector:
            action: {}
        button_four_double_press:
          name: Double Press
          description: Action to run on button 4 (Lower-right) double press
          default: []
          selector:
            action: {}
        button_four_long_press:
          name: Long Press
          description: Action to run on button 4 (Lower-right) long press
          default: []
          selector:
            action: {}
  source_url: https://github.com/wiktor2200/ha_blueprints/blob/main/ZHA_Moes_4button_blueprint.yaml
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'tuya_4button_scene_switch'
action:
- variables:
    command: '{{ trigger.event.data.command }}'
    endpoint_id: '{{ trigger.event.data.endpoint_id }}'
- choose:
  - conditions: '{{ command == ''remote_button_short_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_short_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_short_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_short_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_short_press'
  - conditions: '{{ command == ''remote_button_double_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_double_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_double_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_double_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_double_press'
  - conditions: '{{ command == ''remote_button_long_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_long_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_long_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_long_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_long_press'