blueprint:
  name: ZHA - Tuya 4-Button Light Controller MOES
  description: |
    Control two light zones using a Moes 4-Button Scene Switch (TS0044).

    ZONES:
    - Left Side (Btn 1 & 3) controls Light 1
    - Right Side (Btn 2 & 4) controls Light 2

    TOP BUTTONS (1 & 2):
    - Short Press: Set to Normal Brightness (fixed input)
    - Double Press: Increase Brightness
    - Long Press: Set to 100%
    - Note: Top buttons are never affected by Night Mode

    BOTTOM BUTTONS (3 & 4):
    - Short Press: Set to Low Brightness
      * If Night Mode is OFF: Uses fixed Low Brightness input
      * If Night Mode is ON: Uses Night Brightness helper value
    - Double Press: Decrease Brightness
    - Long Press: Turn Off

  domain: automation
  input:
    tuya_4button_scene_switch:
      name: Tuya 4-Button Scene Switch
      description: Tuya 4-Button Scene Switch to use
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_wkai4ga5
          model: TS0044
          multiple: false
    light_one:
      name: Light 1 (Left Side)
      description: Controlled by Button 1 (Top) and Button 3 (Bottom)
      selector:
        entity:
          domain: light
    light_two:
      name: Light 2 (Right Side)
      description: Controlled by Button 2 (Top) and Button 4 (Bottom)
      selector:
        entity:
          domain: light

    # --- Configuration ---
    brightness_normal:
      name: Normal Brightness (Top Short Press)
      description: Fixed brightness % for top buttons. Always used regardless of Night Mode.
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    brightness_low:
      name: Low Brightness (Bottom Short Press)
      description: Fixed brightness % for bottom buttons. Used only when Night Mode is OFF.
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    brightness_step:
      name: Brightness Step
      description: Percentage to increase/decrease on double press.
      default: 20
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    # --- Night Mode Override ---
    helper_night_mode:
      name: Night Mode Helper
      description: Boolean helper. If ON, Bottom Buttons use the Night Helper value. If OFF, they use the Low Brightness input.
      default: input_boolean.night_mode
      selector:
        entity:
          domain: input_boolean
    helper_brightness_night:
      name: Night Brightness Helper
      description: Value used for Bottom Buttons when Night Mode is ON.
      default: input_number.light_brightness_night
      selector:
        entity:
          domain: input_number
  source_url: https://github.com/wiktor2200/ha_blueprints/blob/main/ZHA_Moes_4buttons_lights_blueprint.yaml

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input tuya_4button_scene_switch

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"

      # Inputs
      l1: !input light_one
      l2: !input light_two
      b_norm: !input brightness_normal
      b_low: !input brightness_low
      b_step: !input brightness_step

      # Helpers
      h_night_mode: !input helper_night_mode
      h_bright_night: !input helper_brightness_night

      # LOGIC: Determine Target Light
      # 1 & 3 = Light 1 (Left), 2 & 4 = Light 2 (Right)
      target_light: >
        {% if endpoint_id in [1, 3] %} {{ l1 }}
        {% else %} {{ l2 }}
        {% endif %}

      # LOGIC: Is Top Button?
      is_top: "{{ endpoint_id in [1, 2] }}"

      # LOGIC: Calculate Brightness for Short Press
      # Top Buttons: ALWAYS use b_norm (Normal Brightness input)
      # Bottom Buttons: Check Night Mode. If ON -> Night Helper. If OFF -> Low Input.
      brightness_value: >
        {% if is_top %}
          {{ b_norm }}
        {% else %}
          {% if is_state(h_night_mode, 'on') %}
            {{ states(h_bright_night) | float(1) }}
          {% else %}
            {{ b_low }}
          {% endif %}
        {% endif %}

  - choose:
      # --- SHORT PRESS ---
      # Uses brightness_value (calculated above)
      - conditions: "{{ command == 'remote_button_short_press' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_pct: "{{ brightness_value }}"

      # --- DOUBLE PRESS ---
      # Top: Step Up | Bottom: Step Down
      - conditions: "{{ command == 'remote_button_double_press' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ b_step if is_top else -b_step }}"

      # --- LONG PRESS ---
      # Top: 100% | Bottom: Off
      - conditions: "{{ command == 'remote_button_long_press' }}"
        sequence:
          - choose:
              - conditions: "{{ is_top }}"
                sequence:
                  - action: light.turn_on
                    target:
                      entity_id: "{{ target_light }}"
                    data:
                      brightness_pct: 100
            default:
              - action: light.turn_off
                target:
                  entity_id: "{{ target_light }}"
